### ISSUE TITLE
Python2 or Python 3...xrange or range

### ISSUE THREAD

**Issue by burkesquires** [aqibsaeed/Research-Paper-Categorization#2]
Hello,

When I run the code, the first error I get is that range i snot found as I am running the code in python3. Should this be run in python2? I tried it sklearn was not found.

def preProcessing(features):
    num_titles = features.size
    clean_titles = []
    stops = set(stopwords.words("english"))
    for i in range( 0, num_titles):   < problem is here
        #letters_only = re.sub("[^a-zA-Z]", " ", features[i]) 
        words = features[i].lower().split()
        words = [w.lower() for w in words if not w in stops]  
        clean_titles.append(" ".join(words))
    return clean_titles

**Comment by aqibsaeed** [comment]
I used Python 2.7 and you should use Python 2.7 if you want to replicate the results.  Makesure, you have scikit learn and other libraries mentioned in notebook installed. I recommend [anaconda distribution](https://www.continuum.io/downloads).

**Comment by burkesquires** [comment]
Thank you for such a quick reply! I will try my 2.7 environment out again.
